/**
 * This class is generated by jOOQ
 */
package it.app.datalayer.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParameterRecord extends org.jooq.impl.UpdatableRecordImpl<it.app.datalayer.tables.records.ParameterRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 1610028474;

	/**
	 * Setter for <code>scandirectory.parameter.ID</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>scandirectory.parameter.ID</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>scandirectory.parameter.src_path</code>.
	 */
	public void setSrcPath(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>scandirectory.parameter.src_path</code>.
	 */
	public java.lang.String getSrcPath() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>scandirectory.parameter.dst_path</code>.
	 */
	public void setDstPath(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>scandirectory.parameter.dst_path</code>.
	 */
	public java.lang.String getDstPath() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>scandirectory.parameter.descrizione</code>.
	 */
	public void setDescrizione(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>scandirectory.parameter.descrizione</code>.
	 */
	public java.lang.String getDescrizione() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return it.app.datalayer.tables.Parameter.PARAMETER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return it.app.datalayer.tables.Parameter.PARAMETER.SRC_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return it.app.datalayer.tables.Parameter.PARAMETER.DST_PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return it.app.datalayer.tables.Parameter.PARAMETER.DESCRIZIONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSrcPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDstPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDescrizione();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParameterRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParameterRecord value2(java.lang.String value) {
		setSrcPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParameterRecord value3(java.lang.String value) {
		setDstPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParameterRecord value4(java.lang.String value) {
		setDescrizione(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ParameterRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ParameterRecord
	 */
	public ParameterRecord() {
		super(it.app.datalayer.tables.Parameter.PARAMETER);
	}

	/**
	 * Create a detached, initialised ParameterRecord
	 */
	public ParameterRecord(java.lang.Integer id, java.lang.String srcPath, java.lang.String dstPath, java.lang.String descrizione) {
		super(it.app.datalayer.tables.Parameter.PARAMETER);

		setValue(0, id);
		setValue(1, srcPath);
		setValue(2, dstPath);
		setValue(3, descrizione);
	}
}
