/**
 * This class is generated by jOOQ
 */
package it.app.datalayer.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parameter extends org.jooq.impl.TableImpl<it.app.datalayer.tables.records.ParameterRecord> {

	private static final long serialVersionUID = -170056865;

	/**
	 * The singleton instance of <code>scandirectory.parameter</code>
	 */
	public static final it.app.datalayer.tables.Parameter PARAMETER = new it.app.datalayer.tables.Parameter();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<it.app.datalayer.tables.records.ParameterRecord> getRecordType() {
		return it.app.datalayer.tables.records.ParameterRecord.class;
	}

	/**
	 * The column <code>scandirectory.parameter.ID</code>.
	 */
	public final org.jooq.TableField<it.app.datalayer.tables.records.ParameterRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>scandirectory.parameter.src_path</code>.
	 */
	public final org.jooq.TableField<it.app.datalayer.tables.records.ParameterRecord, java.lang.String> SRC_PATH = createField("src_path", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>scandirectory.parameter.dst_path</code>.
	 */
	public final org.jooq.TableField<it.app.datalayer.tables.records.ParameterRecord, java.lang.String> DST_PATH = createField("dst_path", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>scandirectory.parameter.descrizione</code>.
	 */
	public final org.jooq.TableField<it.app.datalayer.tables.records.ParameterRecord, java.lang.String> DESCRIZIONE = createField("descrizione", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * Create a <code>scandirectory.parameter</code> table reference
	 */
	public Parameter() {
		this("parameter", null);
	}

	/**
	 * Create an aliased <code>scandirectory.parameter</code> table reference
	 */
	public Parameter(java.lang.String alias) {
		this(alias, it.app.datalayer.tables.Parameter.PARAMETER);
	}

	private Parameter(java.lang.String alias, org.jooq.Table<it.app.datalayer.tables.records.ParameterRecord> aliased) {
		this(alias, aliased, null);
	}

	private Parameter(java.lang.String alias, org.jooq.Table<it.app.datalayer.tables.records.ParameterRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, it.app.datalayer.Scandirectory.SCANDIRECTORY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<it.app.datalayer.tables.records.ParameterRecord, java.lang.Integer> getIdentity() {
		return it.app.datalayer.Keys.IDENTITY_PARAMETER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<it.app.datalayer.tables.records.ParameterRecord> getPrimaryKey() {
		return it.app.datalayer.Keys.KEY_PARAMETER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<it.app.datalayer.tables.records.ParameterRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<it.app.datalayer.tables.records.ParameterRecord>>asList(it.app.datalayer.Keys.KEY_PARAMETER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public it.app.datalayer.tables.Parameter as(java.lang.String alias) {
		return new it.app.datalayer.tables.Parameter(alias, this);
	}

	/**
	 * Rename this table
	 */
	public it.app.datalayer.tables.Parameter rename(java.lang.String name) {
		return new it.app.datalayer.tables.Parameter(name, null);
	}
}
