/**
 * This class is generated by jOOQ
 */
package it.app.datalayer;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>scandirectory</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<it.app.datalayer.tables.records.ParameterRecord, java.lang.Integer> IDENTITY_PARAMETER = Identities0.IDENTITY_PARAMETER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<it.app.datalayer.tables.records.ParameterRecord> KEY_PARAMETER_PRIMARY = UniqueKeys0.KEY_PARAMETER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<it.app.datalayer.tables.records.ParameterRecord, java.lang.Integer> IDENTITY_PARAMETER = createIdentity(it.app.datalayer.tables.Parameter.PARAMETER, it.app.datalayer.tables.Parameter.PARAMETER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<it.app.datalayer.tables.records.ParameterRecord> KEY_PARAMETER_PRIMARY = createUniqueKey(it.app.datalayer.tables.Parameter.PARAMETER, it.app.datalayer.tables.Parameter.PARAMETER.ID);
	}
}
