/**
 * This class is generated by jOOQ
 */
package it.app.datalayer;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Scandirectory extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1328166997;

	/**
	 * The singleton instance of <code>scandirectory</code>
	 */
	public static final Scandirectory SCANDIRECTORY = new Scandirectory();

	/**
	 * No further instances allowed
	 */
	private Scandirectory() {
		super("scandirectory");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			it.app.datalayer.tables.Parameter.PARAMETER);
	}
}
