/**
 * This class is generated by jOOQ
 */
package it.app.datalayer;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in scandirectory
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table scandirectory.parameter
	 */
	public static final it.app.datalayer.tables.Parameter PARAMETER = it.app.datalayer.tables.Parameter.PARAMETER;
}
