/**
 * This class is generated by jOOQ
 */
package it.app.datalayer.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ParameterDao extends org.jooq.impl.DAOImpl<it.app.datalayer.tables.records.ParameterRecord, it.app.datalayer.tables.pojos.Parameter, java.lang.Integer> {

	/**
	 * Create a new ParameterDao without any configuration
	 */
	public ParameterDao() {
		super(it.app.datalayer.tables.Parameter.PARAMETER, it.app.datalayer.tables.pojos.Parameter.class);
	}

	/**
	 * Create a new ParameterDao with an attached configuration
	 */
	public ParameterDao(org.jooq.Configuration configuration) {
		super(it.app.datalayer.tables.Parameter.PARAMETER, it.app.datalayer.tables.pojos.Parameter.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(it.app.datalayer.tables.pojos.Parameter object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>ID IN (values)</code>
	 */
	public java.util.List<it.app.datalayer.tables.pojos.Parameter> fetchById(java.lang.Integer... values) {
		return fetch(it.app.datalayer.tables.Parameter.PARAMETER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>ID = value</code>
	 */
	public it.app.datalayer.tables.pojos.Parameter fetchOneById(java.lang.Integer value) {
		return fetchOne(it.app.datalayer.tables.Parameter.PARAMETER.ID, value);
	}

	/**
	 * Fetch records that have <code>src_path IN (values)</code>
	 */
	public java.util.List<it.app.datalayer.tables.pojos.Parameter> fetchBySrcPath(java.lang.String... values) {
		return fetch(it.app.datalayer.tables.Parameter.PARAMETER.SRC_PATH, values);
	}

	/**
	 * Fetch records that have <code>dst_path IN (values)</code>
	 */
	public java.util.List<it.app.datalayer.tables.pojos.Parameter> fetchByDstPath(java.lang.String... values) {
		return fetch(it.app.datalayer.tables.Parameter.PARAMETER.DST_PATH, values);
	}

	/**
	 * Fetch records that have <code>descrizione IN (values)</code>
	 */
	public java.util.List<it.app.datalayer.tables.pojos.Parameter> fetchByDescrizione(java.lang.String... values) {
		return fetch(it.app.datalayer.tables.Parameter.PARAMETER.DESCRIZIONE, values);
	}
}
